### ISSUE TITLE
Repository Secret folder request

### ISSUE THREAD

**Issue by CristianMeza16** [catarizea/bvm-ventilator-covid#2]
Hi!, this message is to request the Secrets folder, since it is not found in the repository, thanks

**Comment by catarizea** [comment]
I've added the README.md file with blog article links. Those are code walkthroughs for each part of the project. You can read about _secret.h_ file at the end of this article [Bluetooth Low Energy Server on ESP32 development board](https://catalin.works/blog/bluetooth-low-energy-server-esp32-development-board/)

**Comment by catarizea** [comment]
I've added to the README.md file the info required to create the BLE UUID variables.
